/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CPSRuntimeModule extends AbstractCPSRuntimeModule {
}
