/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CPSStandaloneSetup extends CPSStandaloneSetupGenerated {

	public static void doSetup() {
		new CPSStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
