/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CPSUiModule extends AbstractCPSUiModule {

	public CPSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
