/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class CPSProposalProvider extends AbstractCPSProposalProvider {
}
